name: My First CI Workflow

on:
  push:
    branches:
      - main

jobs:
  say-hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print a greeting
        run: echo "Hello CI/CD World!"
